CREATE DATABASE CADASTRO_PRODUTOS;

USE CADASTRO_PRODUTOS;

CREATE TABLE PRODUTOS(
  ID INT NOT NULL AUTO_INCREMENT,
  CODIGO INT(8) NOT NULL,
  NOME VARCHAR(50) NOT NULL,
  PRECO DOUBLE NOT NULL,
  QUANTIDADE INT NOT NULL,
  DAT_VALIDADE CHAR(10) NOT NULL,
  DAT_CADASTRO CHAR(10) NOT NULL,
  CATEGORIA VARCHAR(20),
  PRIMARY KEY(ID)
);

INSERT INTO PRODUTOS(CODIGO,NOME,PRECO,QUANTIDADE,DAT_VALIDADE,DAT_CADASTRO,CATEGORIA)
VALUES(27349015,"MACARRÃO",7.89,10,"25/07/2022","21/01/2022","ALIMENTO");

UPDATE PRODUTOS
SET CATEGORIA = "ALIMENTO"
WHERE NOME = "MACARRÃO";